<?php

namespace Database\Seeders;

use App\Enums\Gender;
use App\Models\Teacher;
use Illuminate\Database\Seeder;

class TeacherSeeder extends Seeder
{
    public function run(): void
    {
        $teachers = [
            [
                'nip' => null,
                'title_prefix' => 'H',
                'name' => 'Yusron Ahmad',
                'nickname' => 'Pak Yusron',
                'title_suffix' => 'S.Th.I.',
                'gender' => Gender::Male,
                'email' => null,
                'phone' => null,
                'address' => 'Jalan Merak Semanding, Tertek, Pare, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => 'KH',
                'name' => 'Mohammad Said Abdus Syukur',
                'nickname' => 'Abah Said',
                'title_suffix' => null,
                'gender' => Gender::Male,
                'email' => null,
                'phone' => null,
                'address' => 'Semanding Tertek Pare Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Ismail',
                'nickname' => 'Pak Mail',
                'title_suffix' => 'S.Ag., S.Pd.I., MA.',
                'gender' => Gender::Male,
                'email' => 'ismailvivohp@gmail.com',
                'phone' => null,
                'address' => 'Jl. Tabrani 55 RT. 10 RW. 3 Bringin, Badas, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Chasan Rochmat',
                'nickname' => 'Pak Chasan',
                'title_suffix' => 'M.Pd.I., AH.',
                'gender' => Gender::Male,
                'email' => null,
                'phone' => null,
                'address' => 'Payak Santren Ngoro Jombang',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'M. Syaifuddin',
                'nickname' => 'Pak Syaif',
                'title_suffix' => 'S.Pd.I.',
                'gender' => Gender::Male,
                'email' => null,
                'phone' => null,
                'address' => 'Dsn.Pogar Rt/Rw 003/014 Tunglur Badas Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => "Nur Muzaro'ah",
                'nickname' => 'Bu Nur',
                'title_suffix' => 'S.Pd.',
                'gender' => Gender::Female,
                'email' => 'nurbaru933@gmail.com',
                'phone' => null,
                'address' => 'Kencong Tengah RT/RW 02/06 Kencong, Kepung, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Abdul Munib',
                'nickname' => 'Pak Munib',
                'title_suffix' => 'M.Pd.I., AH.',
                'gender' => Gender::Male,
                'email' => 'dulmunieb5758@gmail.com',
                'phone' => null,
                'address' => 'Plemahan, Banyuarang, Ngoro, Jombang',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Anik Sulistyanik',
                'nickname' => 'Bu Anik',
                'title_suffix' => 'S.Pd.',
                'gender' => Gender::Female,
                'email' => 'aniksulis2602@gmail.com',
                'phone' => null,
                'address' => 'Jl. Flamboyan 83 A Tulungrejo, Pare, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => "Mohammad Irza' Asmoe'i",
                'nickname' => 'Pak Irza',
                'title_suffix' => 'SE., MM.',
                'gender' => Gender::Male,
                'email' => 'irzalilik@gmail.com',
                'phone' => null,
                'address' => 'Jl. Raya Pare - Wates Dsn. Plosorejo S. Agung, Plosoklaten, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Edy Subroto',
                'nickname' => 'Pak Edy',
                'title_suffix' => 'S.Pd.',
                'gender' => Gender::Male,
                'email' => null,
                'phone' => null,
                'address' => 'Gadungan, Puncu, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Anjariyati Masruroh',
                'nickname' => 'Bu Anjar',
                'title_suffix' => 'SE., MM.',
                'gender' => Gender::Female,
                'email' => 'anjaryatimasruroh@gmail.com',
                'phone' => null,
                'address' => 'Dampit, Asmorobangun, Puncu, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Dhuha Rohmawan',
                'nickname' => 'Pak Dhuha',
                'title_suffix' => 'M.Pd.I.',
                'gender' => Gender::Male,
                'email' => null,
                'phone' => null,
                'address' => 'Jl. Bagawanta Bhari, Semanding, Tertek, Pare, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => "Riyadlul Badi'ah",
                'nickname' => 'Bu Badi',
                'title_suffix' => 'S.Th.I.',
                'gender' => Gender::Female,
                'email' => 'riyadlulbadiah2@gmail.com',
                'phone' => null,
                'address' => 'Jl. Bagawanta Bhari, Semanding, Tertek, Pare, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Fahrun Nuha',
                'nickname' => 'Pak Nuha',
                'title_suffix' => 'S.Pd.I.',
                'gender' => Gender::Male,
                'email' => 'fahru.ahmed.husein@gmail.com',
                'phone' => null,
                'address' => 'Jl. Gajah Mada RT/RW 002/021 Tertek, Pare, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Nurul Ismah',
                'nickname' => 'Ning Ismah',
                'title_suffix' => 'S.H., AH.',
                'gender' => Gender::Female,
                'email' => null,
                'phone' => null,
                'address' => 'Jalan Merak Semanding, Tertek, Pare, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Dewi Maesarotul Mufidah',
                'nickname' => 'Bu Pipit',
                'title_suffix' => 'S.Pd.I., AH.',
                'gender' => Gender::Female,
                'email' => 'dewymufidah114@gmail.com',
                'phone' => null,
                'address' => 'Semanding Tertek Pare Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Zesi Selly Dewanti',
                'nickname' => 'Bu Zesi',
                'title_suffix' => 'S.Pd.',
                'gender' => Gender::Female,
                'email' => 'zesiselly11@gmail.com',
                'phone' => null,
                'address' => 'Tegowangi Plemahan Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Syamsul Arifin',
                'nickname' => 'Pak Syamsul',
                'title_suffix' => 'M.Pd.',
                'gender' => Gender::Female,
                'email' => 'asyamsul045@gmail.com',
                'phone' => null,
                'address' => 'Sumberagung Plosoklaten Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Zeni Pangestu',
                'nickname' => 'Bu Zeni',
                'title_suffix' => 'S.Pd.',
                'gender' => Gender::Female,
                'email' => 'zenipangestu08@gmail.com',
                'phone' => null,
                'address' => 'Dsn. Bungkul RT 02 RW 06 Kec. Kunjang Kab. Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Richayatul Husna',
                'nickname' => 'Bu Richa',
                'title_suffix' => 'M.Pd.',
                'gender' => Gender::Female,
                'email' => 'richahusna@gmail.com',
                'phone' => null,
                'address' => 'Kwagean Krenceng Kepung Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Nizaruddin Ahmad',
                'nickname' => 'Pak Nizar',
                'title_suffix' => 'S.Pd.I.',
                'gender' => Gender::Male,
                'email' => 'nizarpajero@gmail.com',
                'phone' => null,
                'address' => 'Dadapan, Solokuro, Lamongan',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => 'Dr',
                'name' => 'Mustajib',
                'nickname' => 'Pak Mustajib',
                'title_suffix' => 'M.Pd.I.',
                'gender' => Gender::Male,
                'email' => 'moestajib86@gmail.com',
                'phone' => null,
                'address' => 'Canggu Badas Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Lia Khusna',
                'nickname' => 'Ning Lia',
                'title_suffix' => null,
                'gender' => Gender::Female,
                'email' => null,
                'phone' => null,
                'address' => 'Jalan Merak Semanding, Tertek, Pare, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Muhammad Kholilul Rohman',
                'nickname' => 'Pak Ilul',
                'title_suffix' => 'S.Hum.',
                'gender' => Gender::Male,
                'email' => null,
                'phone' => null,
                'address' => 'Sidomulyo Puncu Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Filanurul Millati Hidayah',
                'nickname' => 'Bu Fila',
                'title_suffix' => 'S.Pd.',
                'gender' => Gender::Female,
                'email' => 'fillahnurul@gmail.com',
                'phone' => null,
                'address' => 'Puhjarak Plemahan Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Kusairi',
                'nickname' => 'Pak Kusairi',
                'title_suffix' => 'S.Pd.I.',
                'gender' => Gender::Female,
                'email' => null,
                'phone' => null,
                'address' => 'Nglamong Karang tengah Kandangan Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'M. Niam',
                'nickname' => 'Pak Niam',
                'title_suffix' => 'S.Pd.I.',
                'gender' => Gender::Male,
                'email' => 'niamaccess@gmail.com',
                'phone' => null,
                'address' => 'Jl. Glagah No. 88 Tulungrejo Pare Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Rofiq Lukmanurrakhim',
                'nickname' => 'Pak Rofiq',
                'title_suffix' => 'S.Pd.',
                'gender' => Gender::Male,
                'email' => 'rofiqlukman145@gmail.com',
                'phone' => null,
                'address' => 'Surowono Canggu Badas Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Binti Sholihatin',
                'nickname' => 'Bu Binti',
                'title_suffix' => 'S.Pd.',
                'gender' => Gender::Female,
                'email' => 'bintisholikatin@gmail.com',
                'phone' => null,
                'address' => 'Jl. Gatot Subroto RT001/RW004 Sumberbendo Pare Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Moh. Irfanudin',
                'nickname' => 'Pak Irfan',
                'title_suffix' => 'S.Pd.',
                'gender' => Gender::Male,
                'email' => 'mirfanuddin02@gmail.com',
                'phone' => null,
                'address' => 'RT 01/ RW 06 Tertek Pare Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Muhammad Ihsanul Hakim',
                'nickname' => 'Pak Ishan',
                'title_suffix' => 'S.Ag.',
                'gender' => Gender::Male,
                'email' => 'sanoeljadoel@gmail.com',
                'phone' => null,
                'address' => 'Juwah Siman Kepung Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Ervina',
                'nickname' => 'Bu Vina',
                'title_suffix' => 'S.Psi.',
                'gender' => Gender::Female,
                'email' => 'ervinayusron87@gmail.com',
                'phone' => null,
                'address' => 'Jl. Merak No 10 Semanding Tertek Pare Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => "Muhibbatul Ilmi Mu'awanah",
                'nickname' => 'Bu Ilmi',
                'title_suffix' => 'M.Pd.I.',
                'gender' => Gender::Female,
                'email' => 'ilmimuhibbatul@gmail.com',
                'phone' => null,
                'address' => 'Jl. Brantas No.40 Ds Pelem Kec. Pare Kab. Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Dhea Firsty Al Farabi',
                'nickname' => 'Bu Dhea',
                'title_suffix' => 'S.Pd.',
                'gender' => Gender::Female,
                'email' => 'dheafirsty@gmail.com',
                'phone' => null,
                'address' => 'Perumahan Jombangan Asri Blok D.13 Tertek Pare Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Samsul Komarudin',
                'nickname' => 'Pak Komar',
                'title_suffix' => 'S.Pd.',
                'gender' => Gender::Male,
                'email' => 'samskomarudin24@gmail.com',
                'phone' => null,
                'address' => 'Jl. Sikatan No. 15 Mangiran, Lamong, Badas, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Elfa Lailis Fika Rohmatika',
                'nickname' => 'Bu Elfa',
                'title_suffix' => null,
                'gender' => Gender::Female,
                'email' => 'elfapsikologi18@gmail.com',
                'phone' => null,
                'address' => 'Jl. Bagawanta bari RT.001 RW.019 Tertek, Pare, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Moh. Amirul Huda',
                'nickname' => 'Pak Irul',
                'title_suffix' => null,
                'gender' => Gender::Male,
                'email' => 'irulaero27@gmail.com',
                'phone' => null,
                'address' => 'Perumahan Jombangan Asri Blok D.13 Tertek Pare Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'M. Hafidzon',
                'nickname' => 'Pak Hafidzon',
                'title_suffix' => null,
                'gender' => Gender::Male,
                'email' => 'mhafidzon@gmail.com',
                'phone' => null,
                'address' => 'RT.01 RW.03 Ngrangkok Klampisan Kandangan Kediri Jawa Timur',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Roudlotul Choiriyah',
                'nickname' => 'Bu Choir',
                'title_suffix' => 'S.Sosio.',
                'gender' => Gender::Female,
                'email' => 'roudlotulchoiriyah@gmail.com',
                'phone' => null,
                'address' => 'Dsn. Karangtengah Ds. Karang Tengah Kandangan Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Muhamad Fashoka',
                'nickname' => 'Pak Fashokha',
                'title_suffix' => 'S.H., AH.',
                'gender' => Gender::Male,
                'email' => 'fashokhaahmad424@gmail.com',
                'phone' => null,
                'address' => 'Dsn. Tunge Ds. Tunge Wates Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Nofi Eriana Sulistiani',
                'nickname' => 'Bu Nofi',
                'title_suffix' => 'S.Pd.',
                'gender' => Gender::Female,
                'email' => 'nofieriana@gmail.com',
                'phone' => null,
                'address' => 'Dsn. Pulorejo Ds. Krecek Badas Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Moh. Riyan Buqhori',
                'nickname' => 'Pak Riyan',
                'title_suffix' => 'S.Psi.',
                'gender' => Gender::Male,
                'email' => 'mriyanbuqhori@gmail.com',
                'phone' => null,
                'address' => 'Jl. Bagawanta Bhari, Semanding, Tertek, Pare, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Muji Indah Rahayu',
                'nickname' => 'Bu Muji',
                'title_suffix' => 'S.Pd.',
                'gender' => Gender::Female,
                'email' => 'indahramadhani0205@gmail.com',
                'phone' => null,
                'address' => 'Jl. Dukuh Pakis 6A2 No. 48 Kec. Dukuh Pakis Kota Surabaya',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Ana Nabilatun Naja',
                'nickname' => 'Bu Ana',
                'title_suffix' => 'AH.',
                'gender' => Gender::Female,
                'email' => null,
                'phone' => null,
                'address' => 'Banaran, Tunglur, Badas, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => "Moh. Hasyim Asy'ari",
                'nickname' => 'Pak Hasyim',
                'title_suffix' => 'S.Pd.I.',
                'gender' => Gender::Male,
                'email' => null,
                'phone' => null,
                'address' => 'Besuk, Koniten, Mojo, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => "Ahmad Burhanudin Nuron A'la",
                'nickname' => 'Pak Burhan',
                'title_suffix' => 'S.Sos.',
                'gender' => Gender::Male,
                'email' => 'ab37786@gmail.com',
                'phone' => null,
                'address' => 'Dsn. Gadungan Barat, Gadungan, Puncu, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Inayatul Karimah Amaliah',
                'nickname' => 'Bu Inayatul',
                'title_suffix' => 'AH.',
                'gender' => Gender::Female,
                'email' => null,
                'phone' => null,
                'address' => null,
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Siti Khuzaimah',
                'nickname' => 'Bu Zaim',
                'title_suffix' => null,
                'gender' => Gender::Female,
                'email' => null,
                'phone' => null,
                'address' => 'Jl. Podang No. 3 Semanding, Tertek, Pare, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => "Zidni Karimatan Nisa'",
                'nickname' => 'Bu Zidni',
                'title_suffix' => null,
                'gender' => Gender::Female,
                'email' => null,
                'phone' => null,
                'address' => 'Jl. Kalimantan RT/RW 001/010 Talun, Gedangsewu, Pare, Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => 'Miftakhul Jannah',
                'nickname' => 'Bu Mifta',
                'title_suffix' => null,
                'gender' => Gender::Female,
                'email' => null,
                'phone' => null,
                'address' => 'Dsn.Pogar Rt/Rw 003/014 Tunglur Badas Kediri',
                'is_active' => true,
            ],
            [
                'nip' => null,
                'title_prefix' => null,
                'name' => "Gufron As'adi",
                'nickname' => 'Pak Gufron',
                'title_suffix' => null,
                'gender' => Gender::Male,
                'email' => null,
                'phone' => null,
                'address' => 'Jl. Bagawanta Bhari, Semanding, Tertek, Pare, Kediri',
                'is_active' => true,
            ],
        ];

        foreach ($teachers as $teacher) {
            Teacher::create($teacher);
        }
    }
}
